version: '3.8'

services:
  nginx-ssl-proxy:
    image: danieldent/nginx-ssl-proxy
    restart: always
    environment:
      UPSTREAM: web:3000
      SERVERNAME: web:3000
      EXTRANAMES: web:3000,test2.example.com
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/etc/letsencrypt"

  web:
    container_name: FSI-MESSENGER-UPC-SISTEMAS-OPERATIVOS-2024
    restart: always
    build: .
    ports:
      - "5000:3000"
    links:
      - mongo
      - mongo-express
    volumes:
      - .:/usr/src/app

  mongo:
    container_name: FSI-MESSENGER
    image: mongo:latest
    ports:
      - "27017:27017"

  mongo-express:
    image: mongo-express
    ports:
      - "8080:8080"
    depends_on:
      - mongo
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=pass
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=pass